# Gateway Configuration
spring:
  cloud:
    gateway:
      mvc:
        routes:
          # Route for User Service
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/users/**
            filters:
              - PrefixPath=/api/v1

          # Route for Task Service
          - id: task-service
            uri: lb://task-service
            predicates:
              - Path=/tasks/**
            filters:
              - PrefixPath=/api/v1

# Server Configuration
server:
  port: 8080

# Eureka Client Configuration
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

